version: '3'

services:

  dig_etl_engine:
    build: .
    volumes:
      - ./config_docker_sandbox.py:/app/dig-etl-engine/config.py
      - ${DIG_PROJECTS_DIR_PATH}:/shared_data/projects
    ports:
      - "9999:9999"
    networks:
      - dig_net

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - dig_net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_NAME}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - dig_net

  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.1
    environment:
      PATH_CONFIG: /usr/share/logstash/pipeline
    volumes:
      - ./logstash/sandbox/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/sandbox/settings/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - dig_net
    depends_on:
      - kafka
      - elasticsearch

  elasticsearch:
    image: elasticsearch:2.4
    volumes:
#      - ./elasticsearch/sandbox/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./elasticsearch/sandbox/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - dig_net

  sandpaper:
    image: digsandpaper/digsandpaper
    ports:
      - "9876:9876"
    volumes:
      - ./sandpaper/sandbox/config:/etc/sandpaper/sandbox/config
    links:
      - elasticsearch
    entrypoint:
      - bin/start.sh
      - --host
      - 0.0.0.0
      - --endpoint
      - http://elasticsearch:9200
      - --config
      - config/sandpaper.json
    networks:
      - dig_net
    depends_on:
      - elasticsearch

  mydig_ws:
    image: mydig_ws
    environment:
      MYDIG_BACKEND_URL: http://${DOCKER_HOST_NAME}:9879/
    ports:
      - "9879:9879"
      - "9880:9880"
    volumes:
      - ${MYDIG_DIR_PATH}:/app/mydig-webservice # development only
      - ${MYDIG_DIR_PATH}/ws/config_docker.py:/app/mydig-webservice/ws/config.py
      - ${DIG_PROJECTS_DIR_PATH}:/shared_data/projects
      - ${DIG_RESOURCES_DIR_PATH}:/shared_data/dig3-resources
    networks:
      - dig_net

networks:
  dig_net:
    driver: bridge
