version: '3'

services:

  dig_etl_engine:
    image: uscisii2/dig-etl-engine:1.0.0
    volumes:
      - .:/app/dig-etl-engine # development only
      - ./config_docker_sandbox.py:/app/dig-etl-engine/config.py
      - ${DIG_PROJECTS_DIR_PATH}:/shared_data/projects
      - dig3-resources-volume:/shared_data/dig3-resources
      - ./logstash/sandbox/pipeline/:/app/logstash_pipeline
      - ${ETK_DIR_PATH}:/app/etk # development only
    ports:
      - "9999"
    networks:
      - dig_net

  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "2181"
    networks:
      - dig_net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka # ${DOCKER_HOST_NAME}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "test:1:1" # development only
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      dig_net:
        # can not set ip range in docker-compose v3 to whitelist fixed ip
        # so set it to 200, DNS still works
        ipv4_address: 172.19.0.200

  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.1
    environment:
      PATH_CONFIG: /usr/share/logstash/pipeline
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - ./logstash/sandbox/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/sandbox/settings/logstash.yml:/usr/share/logstash/config/logstash.yml
    networks:
      - dig_net
    depends_on:
      - kafka
      - elasticsearch

  elasticsearch:
    image: elasticsearch:2.4
    volumes:
#      - ./elasticsearch/sandbox/config/logging.yml:/usr/share/elasticsearch/config/logging.yml
      - ./elasticsearch/sandbox/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - dig_net

  sandpaper:
    image: digsandpaper/digsandpaper
    ports:
      - "9876"
    volumes:
      - ./sandpaper/sandbox/config:/etc/sandpaper/config
    links:
      - elasticsearch
    entrypoint:
      - bin/start.sh
      - --host
      - 0.0.0.0
      - --endpoint
      - http://elasticsearch:9200
      - --config
      - config/sandpaper.json
    networks:
      - dig_net
    depends_on:
      - elasticsearch

  mydig_ws:
    image: uscisii2/mydig_ws:1.0.0
#    environment:
#      MYDIG_BACKEND_URL: http://${DOCKER_HOST_NAME}:9879/
    ports:
      - "9879:9879"
      - "9880:9880"
    volumes:
      - ./mydig-webservice/sandbox/config_docker.py:/app/mydig-webservice/ws/config.py
#      - ${MYDIG_DIR_PATH}:/app/mydig-webservice # development only
#      - ${MYDIG_DIR_PATH}/ws/config_docker.py:/app/mydig-webservice/ws/config.py # development only
      - dig3-resources-volume:/shared_data/projects
      - ${DIG_RESOURCES_DIR_PATH}:/shared_data/dig3-resources
    networks:
      - dig_net

  digui:
    image: digmemex/digui:0.0.57
    ports:
      - "8080" # behind nginx, only expose to inner network
    volumes:
      - ./digapp/sandbox/logs/digapp:/var/log
    environment:
      NODE_ENV: 'production' # for port 8080
      ES_HOST: '{"host": "http://localhost:8089/elasticsearchsample"}'
      DATABASE_TYPE: 'sample'
      CONFIG_ENDPOINT: 'http://localhost:8089/projects/'
      TAGS_ENTITY_ENDPOINT: 'http://localhost:8089/projects/PROJECT/tags/TAG/annotations/Ad/annotations'
      TAGS_EXTRACTION_ENDPOINT: 'http://localhost:8089/projects/PROJECT/entities/ENTITY_ID/fields/EXTRACTION_FIELD/annotations'
      TAGS_LIST_ENDPOINT: 'http://localhost:8089/projects/PROJECT/tags'
      SEARCH_CONFIG: '{
        "http://sandpaper:9876": "http://localhost:8089/search9876"
      }'
    networks:
      - dig_net

  nginxdigapp3:
    image: nginx
    links:
      - digui:digui
    ports:
      - "8089:80"
    volumes:
      - ./digapp/sandbox/conf/nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./digapp/sandbox/conf/nginx_sites_enabled/dig.conf:/etc/nginx/conf.d/default.conf
      - ./digapp/sandbox/logs/nginx:/var/log/nginx
      - ./digapp/sandbox/logs/digapp:/var/log/diglogs
    depends_on:
      - elasticsearch
    networks:
      - dig_net

networks:
  dig_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24

volumes:
  dig3-resources-volume: