version: '3'

services:

  nginx:
    volumes:
      - ./nginx/sandbox/nginx/.htpasswd:/etc/nginx/.htpasswd

  dig_etl_engine:
    volumes:
      - .:/app/dig-etl-engine
      - ${ETK_DIR_PATH}:/app/etk

  mydig_ws:
    volumes:
      - ${MYDIG_DIR_PATH}:/app/mydig-webservice
      - ${ETK_DIR_PATH}:/app/etk
#      - ${SPACY_DIR_PATH}:/app/spacy-ui
