version: '3'

services:

  dig_etl_engine:
    build: .
    volumes:
      - ./config_docker_sandbox.py:/app/dig-etl-engine/config.py
      - ./../mydig-projects:/projects_data
    ports:
      - "9999:9999"
    networks:
      - dig_net

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - dig_net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - dig_net

networks:
  dig_net:
    driver: bridge
