cluster.name: "docker-cluster"
network.host: 0.0.0.0
index.number_of_replicas: 0


xpack.security.enabled: false
xpack.monitoring.enabled: false
xpack.ml.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false
